### ISSUE TITLE
Realm 3.0 compatibility

### ISSUE THREAD

**Issue by Greensource** [PoissonBallon/EasyRealm#4]
the pod EasyRealm is not compatible with Realm 3.x. 

- `RealmSwift (= 3.0.2)` required by `Podfile.lock`
- `RealmSwift (~> 2.4)` required by `EasyRealm (2.0.1)`

**Comment by PoissonBallon** [comment]
- Update compatibility with Realm 3.0.0
- Update compatibility with Swift 3.2 and 4.0
- New 3.0.0 version available

https://github.com/PoissonBallon/EasyRealm/pull/5
